<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbqNV0T\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbqNV0T/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFbqNV0T.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFbqNV0T\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFbqNV0T\App_KernelProdContainer([
    'container.build_hash' => 'FbqNV0T',
    'container.build_id' => '5e009d99',
    'container.build_time' => 1670404717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbqNV0T');
